services:
  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    image: mariadb:1337
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    build: ./requirements/wordpress
    image: wordpress:1337
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    ports:
      - "9000:9000"
  nginx:
    container_name:  nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:1337
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
networks:
  inception:
    driver: bridge

volumes:
    wp:
      name : wp
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/snagat/data/wp
    db:
      name : db
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/snagat/data/db
  